name: chungmo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dio: ^5.8.0+1
  dotlottie_loader: ^0.0.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get: ^4.7.2
  get_it: ^8.0.3
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.3.0
  murmur3: ^2.1.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  permission_handler: ^11.4.0
  sqflite: ^2.4.2
  table_calendar: ^3.1.3
  timezone: ^0.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/analyze.lottie
