/// Measures test coverage honestly, and prints where it is thin.
///
/// `flutter test --coverage` reports only the libraries a test actually
/// loaded. A file no test imports is therefore absent from `lcov.info`
/// rather than scored zero, and the files with no tests are exactly the
/// ones that vanish — which inflates the total. This script writes a
/// temporary test that imports every library, so the whole package is in
/// the report, then drops generated code before counting.
///
/// Usage (from the repository root):
///
///   fvm dart run tool/coverage.dart [options]
///
/// Options:
///   --html          also render coverage/html with genhtml (needs lcov)
///   --min=NN        exit non-zero if the total falls below NN percent
///   --no-run        reuse the existing coverage/lcov.info, only re-report
library;

import 'dart:io';

/// Suffixes of code nobody writes by hand. Counting it measures the code
/// generators, not the tests.
const List<String> _generated = [
  '.g.dart',
  '.freezed.dart',
  '.config.dart',
  '.mocks.dart',
  'firebase_options.dart',
];

const String _helperPath = 'test/coverage_helper_test.dart';

Future<void> main(List<String> args) async {
  final bool html = args.contains('--html');
  final bool run = !args.contains('--no-run');
  final String? minArg = args
      .where((a) => a.startsWith('--min='))
      .map((a) => a.substring('--min='.length))
      .firstOrNull;
  final double? min = minArg == null ? null : double.parse(minArg);

  if (!Directory('lib').existsSync() || !Directory('test').existsSync()) {
    stderr.writeln('Run this from the repository root.');
    exit(2);
  }

  if (run) {
    final List<File> libraries = _libraries();
    _writeHelper(libraries);
    stdout.writeln('Importing ${libraries.length} libraries for coverage.');
    try {
      final int code = await _runTests();
      if (code != 0) {
        stderr.writeln('\nTests failed; coverage not reported.');
        exit(code);
      }
    } finally {
      // Never leave it behind: committed, it would go stale the moment a
      // file is added, and quietly under-report again.
      File(_helperPath).deleteSync();
    }
  }

  final File lcov = File('coverage/lcov.info');
  if (!lcov.existsSync()) {
    stderr.writeln('No coverage/lcov.info. Drop --no-run to produce one.');
    exit(2);
  }

  final List<_Record> all = _parse(lcov.readAsStringSync());
  final List<_Record> kept =
      all.where((r) => !_isGenerated(r.path)).toList(growable: false);
  // Rewrite the report without generated code, so genhtml and the editor
  // gutters show the same set these numbers describe.
  lcov.writeAsStringSync(kept.map((r) => r.raw).join());

  _report(all, kept);

  if (html) await _genhtml();

  final double total = _percent(kept);
  if (min != null && total + 0.05 < min) {
    stderr.writeln(
        '\nCoverage ${total.toStringAsFixed(1)}% is below the required $min%.');
    exit(1);
  }
}

/// Every library under `lib/`, excluding `part` files — those cannot be
/// imported, and they are covered through the library that owns them.
List<File> _libraries() {
  final files = Directory('lib')
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.dart'))
      .where((f) => !_isPart(f))
      .toList();
  files.sort((a, b) => a.path.compareTo(b.path));
  return files;
}

bool _isPart(File file) {
  for (final line in file.readAsLinesSync()) {
    final String trimmed = line.trim();
    if (trimmed.isEmpty || trimmed.startsWith('//')) continue;
    return trimmed.startsWith('part of');
  }
  return false;
}

void _writeHelper(List<File> libraries) {
  final imports = libraries
      .map(
          (f) => "import 'package:chungmo/${f.path.substring('lib/'.length)}';")
      .join('\n');
  File(_helperPath).writeAsStringSync('''
// GENERATED by tool/coverage.dart — not committed, do not edit.
//
// Importing every library puts them all in lcov.info, including the ones
// no other test touches. Without this they are missing from the report
// rather than scored zero, and the total reads higher than it is.
// ignore_for_file: unused_import, directives_ordering
$imports

import 'package:flutter_test/flutter_test.dart';

void main() {
  // The imports above are the point; this keeps the file a valid test.
  test('every library is loaded for coverage', () => expect(true, isTrue));
}
''');
}

Future<int> _runTests() async {
  // Honour the pinned SDK the way the rest of the project does.
  final String executable =
      Platform.environment['FLUTTER'] ?? (_has('fvm') ? 'fvm' : 'flutter');
  final List<String> arguments = executable == 'fvm'
      ? ['flutter', 'test', '--coverage']
      : ['test', '--coverage'];
  final process = await Process.start(executable, arguments,
      mode: ProcessStartMode.inheritStdio);
  return process.exitCode;
}

bool _has(String command) => Process.runSync('which', [command]).exitCode == 0;

Future<void> _genhtml() async {
  if (!_has('genhtml')) {
    stdout.writeln('\ngenhtml not found; install it with `brew install lcov`.');
    return;
  }
  await Process.start('genhtml', ['coverage/lcov.info', '-o', 'coverage/html'],
          mode: ProcessStartMode.inheritStdio)
      .then((p) => p.exitCode);
  stdout.writeln('\nWrote coverage/html/index.html');
}

bool _isGenerated(String path) => _generated.any(path.endsWith);

class _Record {
  final String path;
  final int hit;
  final int found;

  /// The original block, so the filtered report stays a valid lcov file.
  final String raw;

  const _Record(this.path, this.hit, this.found, this.raw);
}

List<_Record> _parse(String lcov) {
  final records = <_Record>[];
  for (final block in lcov.split('end_of_record')) {
    final path = RegExp(r'SF:(.+)').firstMatch(block)?.group(1)?.trim();
    if (path == null) continue;
    final hit = int.parse(RegExp(r'LH:(\d+)').firstMatch(block)!.group(1)!);
    final found = int.parse(RegExp(r'LF:(\d+)').firstMatch(block)!.group(1)!);
    records.add(_Record(path, hit, found, '${block}end_of_record'));
  }
  return records;
}

double _percent(List<_Record> records) {
  final int found = records.fold(0, (sum, r) => sum + r.found);
  if (found == 0) return 0;
  return records.fold(0, (int sum, r) => sum + r.hit) / found * 100;
}

void _report(List<_Record> all, List<_Record> kept) {
  final int generated = all.length - kept.length;
  stdout
    ..writeln('\n${'=' * 62}')
    ..writeln('Coverage: ${_percent(kept).toStringAsFixed(1)}%  '
        '(${kept.fold(0, (int s, r) => s + r.hit)}/'
        '${kept.fold(0, (int s, r) => s + r.found)} lines, '
        '${kept.length} files; $generated generated files excluded)')
    ..writeln('=' * 62);

  // Grouped by directory, worst first: the point of the number is to say
  // where to go next.
  final groups = <String, List<int>>{};
  for (final r in kept) {
    final parts = r.path.split('/');
    final key = parts.length > 3 ? parts.take(3).join('/') : r.path;
    final entry = groups.putIfAbsent(key, () => [0, 0]);
    entry[0] += r.hit;
    entry[1] += r.found;
  }
  final ordered = groups.entries.where((e) => e.value[1] > 0).toList()
    ..sort(
        (a, b) => (a.value[0] / a.value[1]).compareTo(b.value[0] / b.value[1]));
  stdout.writeln('\nBy area, thinnest first:');
  for (final e in ordered) {
    final pct = e.value[0] / e.value[1] * 100;
    stdout.writeln('  ${e.key.padRight(40)} '
        '${'${e.value[0]}/${e.value[1]}'.padLeft(10)}  '
        '${pct.toStringAsFixed(1).padLeft(5)}%');
  }

  final untouched = kept.where((r) => r.found > 0 && r.hit == 0).toList()
    ..sort((a, b) => b.found.compareTo(a.found));
  if (untouched.isNotEmpty) {
    stdout.writeln('\nNo coverage at all (largest first):');
    for (final r in untouched) {
      stdout.writeln('  ${r.path.padRight(50)} ${r.found} lines');
    }
  }
}

extension<T> on Iterable<T> {
  T? get firstOrNull => isEmpty ? null : first;
}
