// Mocks generated by Mockito 5.4.6 from annotations
// in chungmo/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:typed_data' as _i15;

import 'package:chungmo/core/analytics/analytics_service.dart' as _i10;
import 'package:chungmo/core/services/notification_service.dart' as _i9;
import 'package:chungmo/data/models/schedule/schedule_model.dart' as _i2;
import 'package:chungmo/data/sources/local/schedule_local_source.dart' as _i12;
import 'package:chungmo/data/sources/remote/pay_recommendation_source.dart'
    as _i16;
import 'package:chungmo/data/sources/remote/schedule_remote_source.dart'
    as _i14;
import 'package:chungmo/domain/entities/invitation_image.dart' as _i18;
import 'package:chungmo/domain/entities/pay_recommendation.dart' as _i3;
import 'package:chungmo/domain/entities/schedule.dart' as _i6;
import 'package:chungmo/domain/repositories/pay_recommendation_repository.dart'
    as _i7;
import 'package:chungmo/domain/repositories/schedule_repository.dart' as _i5;
import 'package:chungmo/domain/usecases/usecases.dart' as _i8;
import 'package:chungmo/presentation/bloc/create/create_cubit.dart' as _i11;
import 'package:flutter_bloc/flutter_bloc.dart' as _i19;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:timezone/timezone.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeScheduleModel_0 extends _i1.SmartFake implements _i2.ScheduleModel {
  _FakeScheduleModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayRecommendation_1 extends _i1.SmartFake
    implements _i3.PayRecommendation {
  _FakePayRecommendation_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterLocalNotificationsPlugin_2 extends _i1.SmartFake
    implements _i4.FlutterLocalNotificationsPlugin {
  _FakeFlutterLocalNotificationsPlugin_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScheduleRepository_3 extends _i1.SmartFake
    implements _i5.ScheduleRepository {
  _FakeScheduleRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSchedule_4 extends _i1.SmartFake implements _i6.Schedule {
  _FakeSchedule_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayRecommendationRepository_5 extends _i1.SmartFake
    implements _i7.PayRecommendationRepository {
  _FakePayRecommendationRepository_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnalyzeLinkUsecase_6 extends _i1.SmartFake
    implements _i8.AnalyzeLinkUsecase {
  _FakeAnalyzeLinkUsecase_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnalyzeImageUsecase_7 extends _i1.SmartFake
    implements _i8.AnalyzeImageUsecase {
  _FakeAnalyzeImageUsecase_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnalyzeTextUsecase_8 extends _i1.SmartFake
    implements _i8.AnalyzeTextUsecase {
  _FakeAnalyzeTextUsecase_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveScheduleUsecase_9 extends _i1.SmartFake
    implements _i8.SaveScheduleUsecase {
  _FakeSaveScheduleUsecase_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationService_10 extends _i1.SmartFake
    implements _i9.NotificationService {
  _FakeNotificationService_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWatchAllSchedulesUsecase_11 extends _i1.SmartFake
    implements _i8.WatchAllSchedulesUsecase {
  _FakeWatchAllSchedulesUsecase_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnalyticsService_12 extends _i1.SmartFake
    implements _i10.AnalyticsService {
  _FakeAnalyticsService_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateState_13 extends _i1.SmartFake implements _i11.CreateState {
  _FakeCreateState_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ScheduleLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockScheduleLocalSource extends _i1.Mock
    implements _i12.ScheduleLocalSource {
  MockScheduleLocalSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Stream<List<_i2.ScheduleModel>> get allSchedulesStream =>
      (super.noSuchMethod(
        Invocation.getter(#allSchedulesStream),
        returnValue: _i13.Stream<List<_i2.ScheduleModel>>.empty(),
      ) as _i13.Stream<List<_i2.ScheduleModel>>);

  @override
  _i13.Stream<List<_i2.ScheduleModel>> watchAllSchedules() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAllSchedules,
          [],
        ),
        returnValue: _i13.Stream<List<_i2.ScheduleModel>>.empty(),
      ) as _i13.Stream<List<_i2.ScheduleModel>>);

  @override
  _i13.Future<void> emitAllSchedules() => (super.noSuchMethod(
        Invocation.method(
          #emitAllSchedules,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> saveSchedule(_i2.ScheduleModel? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSchedule,
          [schedule],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> editSchedule(_i2.ScheduleModel? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #editSchedule,
          [schedule],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> deleteScheduleByLink(String? link) => (super.noSuchMethod(
        Invocation.method(
          #deleteScheduleByLink,
          [link],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<_i2.ScheduleModel?> getScheduleByLink(String? link) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScheduleByLink,
          [link],
        ),
        returnValue: _i13.Future<_i2.ScheduleModel?>.value(),
      ) as _i13.Future<_i2.ScheduleModel?>);

  @override
  _i13.Future<List<_i2.ScheduleModel>> getAllSchedulesOnce() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSchedulesOnce,
          [],
        ),
        returnValue:
            _i13.Future<List<_i2.ScheduleModel>>.value(<_i2.ScheduleModel>[]),
      ) as _i13.Future<List<_i2.ScheduleModel>>);

  @override
  _i13.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [ScheduleRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockScheduleRemoteSource extends _i1.Mock
    implements _i14.ScheduleRemoteSource {
  MockScheduleRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.ScheduleModel> fetchScheduleFromServer(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScheduleFromServer,
          [url],
        ),
        returnValue: _i13.Future<_i2.ScheduleModel>.value(_FakeScheduleModel_0(
          this,
          Invocation.method(
            #fetchScheduleFromServer,
            [url],
          ),
        )),
      ) as _i13.Future<_i2.ScheduleModel>);

  @override
  _i13.Future<_i2.ScheduleModel> fetchScheduleFromImage(
    _i15.Uint8List? bytes,
    String? mimeType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScheduleFromImage,
          [
            bytes,
            mimeType,
          ],
        ),
        returnValue: _i13.Future<_i2.ScheduleModel>.value(_FakeScheduleModel_0(
          this,
          Invocation.method(
            #fetchScheduleFromImage,
            [
              bytes,
              mimeType,
            ],
          ),
        )),
      ) as _i13.Future<_i2.ScheduleModel>);

  @override
  _i13.Future<_i2.ScheduleModel> fetchScheduleFromText(String? text) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScheduleFromText,
          [text],
        ),
        returnValue: _i13.Future<_i2.ScheduleModel>.value(_FakeScheduleModel_0(
          this,
          Invocation.method(
            #fetchScheduleFromText,
            [text],
          ),
        )),
      ) as _i13.Future<_i2.ScheduleModel>);
}

/// A class which mocks [PayRecommendationSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPayRecommendationSource extends _i1.Mock
    implements _i16.PayRecommendationSource {
  MockPayRecommendationSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i3.PayRecommendation> fetchRecommendation({
    required _i6.Schedule? target,
    required List<_i6.Schedule>? history,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRecommendation,
          [],
          {
            #target: target,
            #history: history,
          },
        ),
        returnValue:
            _i13.Future<_i3.PayRecommendation>.value(_FakePayRecommendation_1(
          this,
          Invocation.method(
            #fetchRecommendation,
            [],
            {
              #target: target,
              #history: history,
            },
          ),
        )),
      ) as _i13.Future<_i3.PayRecommendation>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i9.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FlutterLocalNotificationsPlugin getLocalNotificationPlugin() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalNotificationPlugin,
          [],
        ),
        returnValue: _FakeFlutterLocalNotificationsPlugin_2(
          this,
          Invocation.method(
            #getLocalNotificationPlugin,
            [],
          ),
        ),
      ) as _i4.FlutterLocalNotificationsPlugin);

  @override
  _i13.Future<void> getPermissions() => (super.noSuchMethod(
        Invocation.method(
          #getPermissions,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> onDidReceiveNotificationResponse({required String? link}) =>
      (super.noSuchMethod(
        Invocation.method(
          #onDidReceiveNotificationResponse,
          [],
          {#link: link},
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> checkPreviousDayForNotify(
          {required _i6.Schedule? schedule}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPreviousDayForNotify,
          [],
          {#schedule: schedule},
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> addNotifySchedule({
    required int? id,
    required String? appName,
    required String? title,
    required _i17.TZDateTime? scheduleDate,
    required String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNotifySchedule,
          [],
          {
            #id: id,
            #appName: appName,
            #title: title,
            #scheduleDate: scheduleDate,
            #payload: payload,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> cancelNotifySchedule({required String? link}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelNotifySchedule,
          [],
          {#link: link},
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> checkScheduledNotifications() => (super.noSuchMethod(
        Invocation.method(
          #checkScheduledNotifications,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> addTestNotifySchedule({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTestNotifySchedule,
          [],
          {#id: id},
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [AnalyzeLinkUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyzeLinkUsecase extends _i1.Mock
    implements _i8.AnalyzeLinkUsecase {
  MockAnalyzeLinkUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ScheduleRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeScheduleRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.ScheduleRepository);

  @override
  _i13.Future<_i6.Schedule> execute(String? link) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [link],
        ),
        returnValue: _i13.Future<_i6.Schedule>.value(_FakeSchedule_4(
          this,
          Invocation.method(
            #execute,
            [link],
          ),
        )),
      ) as _i13.Future<_i6.Schedule>);
}

/// A class which mocks [AnalyzeImageUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyzeImageUsecase extends _i1.Mock
    implements _i8.AnalyzeImageUsecase {
  MockAnalyzeImageUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ScheduleRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeScheduleRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.ScheduleRepository);

  @override
  _i13.Future<_i6.Schedule> execute(_i18.InvitationImage? image) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [image],
        ),
        returnValue: _i13.Future<_i6.Schedule>.value(_FakeSchedule_4(
          this,
          Invocation.method(
            #execute,
            [image],
          ),
        )),
      ) as _i13.Future<_i6.Schedule>);
}

/// A class which mocks [AnalyzeTextUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyzeTextUsecase extends _i1.Mock
    implements _i8.AnalyzeTextUsecase {
  MockAnalyzeTextUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ScheduleRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeScheduleRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.ScheduleRepository);

  @override
  _i13.Future<_i6.Schedule> execute(String? text) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [text],
        ),
        returnValue: _i13.Future<_i6.Schedule>.value(_FakeSchedule_4(
          this,
          Invocation.method(
            #execute,
            [text],
          ),
        )),
      ) as _i13.Future<_i6.Schedule>);
}

/// A class which mocks [EditScheduleUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditScheduleUsecase extends _i1.Mock
    implements _i8.EditScheduleUsecase {
  MockEditScheduleUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ScheduleRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeScheduleRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.ScheduleRepository);

  @override
  _i13.Future<void> execute(_i6.Schedule? schedule) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [schedule],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [RecommendPayUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecommendPayUsecase extends _i1.Mock
    implements _i8.RecommendPayUsecase {
  MockRecommendPayUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.PayRecommendationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePayRecommendationRepository_5(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i7.PayRecommendationRepository);

  @override
  _i13.Future<_i3.PayRecommendation> execute(_i6.Schedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [schedule],
        ),
        returnValue:
            _i13.Future<_i3.PayRecommendation>.value(_FakePayRecommendation_1(
          this,
          Invocation.method(
            #execute,
            [schedule],
          ),
        )),
      ) as _i13.Future<_i3.PayRecommendation>);
}

/// A class which mocks [SaveScheduleUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveScheduleUsecase extends _i1.Mock
    implements _i8.SaveScheduleUsecase {
  MockSaveScheduleUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ScheduleRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeScheduleRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.ScheduleRepository);

  @override
  _i13.Future<void> execute(_i6.Schedule? schedule) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [schedule],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [WatchAllSchedulesUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchAllSchedulesUsecase extends _i1.Mock
    implements _i8.WatchAllSchedulesUsecase {
  MockWatchAllSchedulesUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ScheduleRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeScheduleRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.ScheduleRepository);

  @override
  _i13.Stream<List<_i6.Schedule>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i13.Stream<List<_i6.Schedule>>.empty(),
      ) as _i13.Stream<List<_i6.Schedule>>);
}

/// A class which mocks [CreateCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateCubit extends _i1.Mock implements _i11.CreateCubit {
  MockCreateCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.AnalyzeLinkUsecase get analyzeLinkUseCase => (super.noSuchMethod(
        Invocation.getter(#analyzeLinkUseCase),
        returnValue: _FakeAnalyzeLinkUsecase_6(
          this,
          Invocation.getter(#analyzeLinkUseCase),
        ),
      ) as _i8.AnalyzeLinkUsecase);

  @override
  _i8.AnalyzeImageUsecase get analyzeImageUseCase => (super.noSuchMethod(
        Invocation.getter(#analyzeImageUseCase),
        returnValue: _FakeAnalyzeImageUsecase_7(
          this,
          Invocation.getter(#analyzeImageUseCase),
        ),
      ) as _i8.AnalyzeImageUsecase);

  @override
  _i8.AnalyzeTextUsecase get analyzeTextUseCase => (super.noSuchMethod(
        Invocation.getter(#analyzeTextUseCase),
        returnValue: _FakeAnalyzeTextUsecase_8(
          this,
          Invocation.getter(#analyzeTextUseCase),
        ),
      ) as _i8.AnalyzeTextUsecase);

  @override
  _i8.SaveScheduleUsecase get saveScheduleUseCase => (super.noSuchMethod(
        Invocation.getter(#saveScheduleUseCase),
        returnValue: _FakeSaveScheduleUsecase_9(
          this,
          Invocation.getter(#saveScheduleUseCase),
        ),
      ) as _i8.SaveScheduleUsecase);

  @override
  _i9.NotificationService get notificationService => (super.noSuchMethod(
        Invocation.getter(#notificationService),
        returnValue: _FakeNotificationService_10(
          this,
          Invocation.getter(#notificationService),
        ),
      ) as _i9.NotificationService);

  @override
  _i8.WatchAllSchedulesUsecase get watchAllSchedulesUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#watchAllSchedulesUseCase),
        returnValue: _FakeWatchAllSchedulesUsecase_11(
          this,
          Invocation.getter(#watchAllSchedulesUseCase),
        ),
      ) as _i8.WatchAllSchedulesUsecase);

  @override
  _i10.AnalyticsService get analytics => (super.noSuchMethod(
        Invocation.getter(#analytics),
        returnValue: _FakeAnalyticsService_12(
          this,
          Invocation.getter(#analytics),
        ),
      ) as _i10.AnalyticsService);

  @override
  set analyzeLinkUseCase(_i8.AnalyzeLinkUsecase? value) => super.noSuchMethod(
        Invocation.setter(
          #analyzeLinkUseCase,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set analyzeImageUseCase(_i8.AnalyzeImageUsecase? value) => super.noSuchMethod(
        Invocation.setter(
          #analyzeImageUseCase,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set analyzeTextUseCase(_i8.AnalyzeTextUsecase? value) => super.noSuchMethod(
        Invocation.setter(
          #analyzeTextUseCase,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set saveScheduleUseCase(_i8.SaveScheduleUsecase? value) => super.noSuchMethod(
        Invocation.setter(
          #saveScheduleUseCase,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set notificationService(_i9.NotificationService? value) => super.noSuchMethod(
        Invocation.setter(
          #notificationService,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set watchAllSchedulesUseCase(_i8.WatchAllSchedulesUsecase? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #watchAllSchedulesUseCase,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set analytics(_i10.AnalyticsService? value) => super.noSuchMethod(
        Invocation.setter(
          #analytics,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.CreateState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeCreateState_13(
          this,
          Invocation.getter(#state),
        ),
      ) as _i11.CreateState);

  @override
  _i13.Stream<_i11.CreateState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i11.CreateState>.empty(),
      ) as _i13.Stream<_i11.CreateState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void watchUpcomingSchedules() => super.noSuchMethod(
        Invocation.method(
          #watchUpcomingSchedules,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> analyzeLink(
    String? url, {
    String? source = 'manual',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeLink,
          [url],
          {#source: source},
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> analyzeImage(
    _i18.InvitationImage? image, {
    String? source = 'gallery',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeImage,
          [image],
          {#source: source},
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> analyzeText(
    String? text, {
    String? source = 'manual',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeText,
          [text],
          {#source: source},
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void resetState() => super.noSuchMethod(
        Invocation.method(
          #resetState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> checkIfNotification() => (super.noSuchMethod(
        Invocation.method(
          #checkIfNotification,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void emit(_i11.CreateState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i19.Change<_i11.CreateState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
